language: go

go:
  - 1.11.x
  - master

env:
  global:
    - GO111MODULE=on

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script: 
  - go test -race -v ./...

after_success:
  - goveralls -service=travis-ci
